# Generated by Django 4.2.23 on 2025-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barimt',
            name='billId',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='companyId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='lottery',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='storeId',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='subBillId',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
