# Generated by Django 4.2.23 on 2025-08-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0002_barimt_billid_alter_barimt_companyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimt',
            name='companyId',
        ),
        migrations.AddField(
            model_name='barimt',
            name='companyReg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
