# Generated by Django 4.2.23 on 2025-08-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0003_remove_barimt_companyid_barimt_companyreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barimt',
            name='companyReg',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
