# Generated by Django 4.2.23 on 2025-08-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0004_alter_barimt_companyreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barimt',
            name='lottery',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
