# Generated by Django 4.2.23 on 2025-08-07 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0005_alter_barimt_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='barimt',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
