# Generated by Django 2.1.7 on 2025-08-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0006_barimt_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimt',
            name='storeId',
        ),
        migrations.AddField(
            model_name='barimt',
            name='storeName',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='barimt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
