# Generated by Django 2.1.7 on 2025-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0007_auto_20250808_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimt',
            name='storeName',
        ),
        migrations.AddField(
            model_name='barimt',
            name='storeNo',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
