# Generated by Django 2.1.7 on 2025-08-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0012_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
