# Generated by Django 2.1.7 on 2025-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0013_auto_20250818_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='barimt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
