# Generated by Django 2.1.7 on 2025-08-19 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barimt_zasvarlagch_app', '0014_barimt_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='barimt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barimt_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barimt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barimt_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
