# Generated by Django 2.1.7 on 2025-08-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0015_auto_20250819_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='barimt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
