# Generated by Django 2.1.7 on 2025-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0016_barimt_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebarimt_zadargaa_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posSid', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRno', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRdate', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRamt', models.IntegerField(default=0)),
                ('citytax', models.IntegerField(default=0)),
                ('posVamt', models.IntegerField(default=0)),
                ('netAmt', models.IntegerField(default=0)),
                ('fromType', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('csmrRegNo', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('csmrName', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posNo', models.IntegerField(default=0)),
                ('operatorName', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('districtCode', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('prParentRno', models.CharField(blank=True, default=0, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebarimt_zadargaa_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posSid', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRno', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRdate', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posRamt', models.IntegerField(default=0)),
                ('citytax', models.IntegerField(default=0)),
                ('posVamt', models.IntegerField(default=0)),
                ('netAmt', models.IntegerField(default=0)),
                ('fromType', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('csmrRegNo', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('csmrName', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('posNo', models.IntegerField(default=0)),
                ('operatorName', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('districtCode', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('prParentRno', models.CharField(blank=True, default=0, max_length=10, null=True)),
            ],
        ),
    ]
