# Generated by Django 2.1.7 on 2025-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barimt_zasvarlagch_app', '0017_ebarimt_zadargaa_0_ebarimt_zadargaa_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='csmrName',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='csmrRegNo',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='fromType',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='posRdate',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='posRno',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='posSid',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
    ]
