# Generated by Django 4.2.26 on 2025-12-09 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barimt_zasvarlagch_app', '0020_auto_20250829_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barimt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_0',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ebarimt_zadargaa_4',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DownloadSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Эхлэх огноо')),
                ('end_date', models.DateField(verbose_name='Дуусах огноо')),
                ('status', models.IntegerField(choices=[(0, 'Нийт борлуулалтын баримт'), (4, 'Багцын толгой баримт')], default=4, verbose_name='Баримтын төрөл')),
                ('download_status', models.CharField(choices=[('pending', 'Хүлээгдэж байна'), ('processing', 'Татагдаж байна'), ('completed', 'Дууссан'), ('failed', 'Алдаа гарсан'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Таталтын төлөв')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Файлын зам')),
                ('total_records', models.IntegerField(default=0, verbose_name='Нийт бичлэг')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Алдааны мэдээлэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Эхэлсэн огноо')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дууссан огноо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Таталтын хуваарь',
                'verbose_name_plural': 'Таталтын хуваарьууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
